name: Docker Images CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            version: [80, 81]
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker Image and Publish
      run: |
          cd php${{ matrix.version }}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u plopix --password-stdin
          docker build . --file Dockerfile --tag ghcr.io/plopix/docker-php-ez-engine/php-${{ matrix.version }}:latest
          docker push ghcr.io/plopix/docker-php-ez-engine/php-${{ matrix.version }}:latest
          docker logout
